### ISSUE TITLE
Exception issues

### ISSUE THREAD

**Issue by Joridan** [bpodgursky/jbool_expressions#11]
Hi,

Thank you a lot for your work, I want to use it in my research job but after compiling with mvn I have a lot of exeption issues.

With this code: 

`		Expression<String> expr = And.of(
		        Variable.of("A"),
		        Variable.of("B"),
		        Or.of(Variable.of("C"), Not.of(Variable.of("C"))));
		    System.out.println(expr);`

I have this exeption: 
`Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Optional
	at com.bpodgursky.jbool_expressions.Not.<init>(Not.java:11)
	at com.bpodgursky.jbool_expressions.Not.of(Not.java:41)
	at src.Main.main(Main.java:148)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Optional
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 3 more`

With this little code:
`	    Expression<String> nonStandard = ExprParser.parse("((A | B) & (C | D))");
	    System.out.println(nonStandard);`

`Exception in thread "main" java.lang.NoClassDefFoundError: org/antlr/runtime/RecognitionException
	at src.Main.main(Main.java:142)
Caused by: java.lang.ClassNotFoundException: org.antlr.runtime.RecognitionException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more`

For moment I don't find any piece of code which works... Could you help me to fix this ?

Thanks a lot,

Joridan

**Comment by bpodgursky** [comment]
It sounds like none of the dependencies are on the java classpath.  You'd probably have best luck running in an IDE, or you could use the maven exec:java goal (see http://stackoverflow.com/questions/9846046/run-main-class-of-maven-project)

If you wanted to run with the raw "java" command, see how to put together a classpath: http://stackoverflow.com/questions/219585/setting-multiple-jars-in-java-classpath.  mvn copy-dependencies will put all the jars somewhere for you: http://stackoverflow.com/questions/8310539/how-to-copy-dependencies-jars-without-test-jars-to-a-directory-using-maven

**Comment by Joridan** [comment]
You were right, the dependencies was needed, I follow the instructions of last link and it works.

Thank you
